/* Conditions checked against mod.json and demonic-triad.c story gates. */
static const Objective objectives[40]={
{"Lekakmod:dark-simon","Dark Simon","Gagner 1 duel contre Heishin."},
{"Lekakmod:destroyer-pegasus","Destroyer Pegasus","Gagner 15 duels contre Pegasus."},
{"Lekakmod:soul-reaper-bakura","Soul Reaper Bakura","Gagner 5 duels contre Dark Simon."},
{"Lekakmod:eclipse-isis","Eclipse Isis","Posséder au moins un Red-eyes B. Dragon (n°82)\ndans le coffre ou le deck."},
{"Lekakmod:primal-rex","Primal Rex","Atteindre 100 victoires au total."},
{"Lekakmod:heishin-the-eternal","Heishin the Eternal","Gagner 1 duel contre Nitemare."},
{"Lekakmod:tyrant-kaiba","Tyrant Kaiba","Débloquer les six premiers duellistes ajoutés :\nDark Simon, Destroyer Pegasus, Soul Reaper Bakura,\nEclipse Isis, Primal Rex et Heishin the Eternal."},
{"Lekakmod:vorthrax","Vorthrax","Débloquer les six premiers duellistes ajoutés :\nDark Simon, Destroyer Pegasus, Soul Reaper Bakura,\nEclipse Isis, Primal Rex et Heishin the Eternal.\nGagner 10 duels contre Primal Rex."},
{"Lekakmod:nemerys","Némérys","Débloquer les six premiers duellistes ajoutés :\nDark Simon, Destroyer Pegasus, Soul Reaper Bakura,\nEclipse Isis, Primal Rex et Heishin the Eternal.\nGagner 10 duels contre Soul Reaper Bakura."},
{"Lekakmod:ignaroth","Ignaroth","Débloquer Tyrant Kaiba, Vorthrax et Némérys.\nGagner 5 duels contre Vorthrax\net 5 contre Némérys."},
{"Lekakmod:vesper","Vesper","Débloquer Ignaroth et gagner 5 duels contre lui.\nAtteindre 200 victoires au total."},
{"Lekakmod:azhur","Azhur","Débloquer Ignaroth et gagner 5 duels contre lui.\nAtteindre 200 victoires au total."},
{"Lekakmod:ferron","Ferron","Débloquer Ignaroth et gagner 5 duels contre lui.\nAtteindre 200 victoires au total."},
{"Lekakmod:nerex","Néréx","Débloquer Vesper.\nDécouvrir 200 cartes différentes dans la bibliothèque.\nGagner 10 duels contre Vesper."},
{"Lekakmod:ravok","Ravok","Débloquer Azhur.\nDécouvrir 200 cartes différentes dans la bibliothèque.\nGagner 10 duels contre Azhur."},
{"Lekakmod:tharn","Tharn","Débloquer Ferron.\nDécouvrir 200 cartes différentes dans la bibliothèque.\nGagner 10 duels contre Ferron."},
{"Lekakmod:zerak","Zerak","Débloquer Tharn.\nDécouvrir Terrorking Archfiend dans la bibliothèque."},
{"Lekakmod:nekris","Nékris","Débloquer Tharn.\nDécouvrir Helpoemer dans la bibliothèque."},
{"Lekakmod:oryx","Oryx","Débloquer Tharn.\nDécouvrir Sea King Dragon (n°443) dans la bibliothèque."},
{"Lekakmod:valtor","Valtor","Débloquer Zerak.\nAtteindre 300 victoires au total."},
{"Lekakmod:serya","Serya","Débloquer Nékris.\nGagner 10 duels contre chacun :\nVesper, Azhur et Ferron."},
{"Lekakmod:drazhen","Drazhen","Débloquer Oryx.\nGagner 10 duels contre chacun :\nNéréx, Ravok et Tharn."},
{"Lekakmod:malvek","Malvek","Débloquer Drazhen.\nDécouvrir Saggi the Dark Clown (n°34)\ndans la bibliothèque."},
{"Lekakmod:nyss","Nyss","Débloquer Drazhen.\nDécouvrir Saggi the Dark Clown (n°34)\ndans la bibliothèque."},
{"Lekakmod:krag","Krag","Débloquer Drazhen.\nDécouvrir Saggi the Dark Clown (n°34)\ndans la bibliothèque."},
{"Lekakmod:velkor","Velkôr","Débloquer Malvek, Nyss et Krag.\nGagner au moins un duel contre chacun\ndes 39 adversaires du jeu original."},
{"Lekakmod:ossyr","Ossyr","Débloquer Malvek, Nyss et Krag.\nGagner au moins un duel contre chacun\ndes 39 adversaires du jeu original."},
{"Lekakmod:nharos","Nharos","Débloquer Malvek, Nyss et Krag.\nGagner au moins un duel contre chacun\ndes 39 adversaires du jeu original."},
{"Lekakmod:solkar","Solkar","Débloquer Velkôr.\nAtteindre 500 victoires au total."},
{"Lekakmod:luneth","Luneth","Débloquer Nharos.\nAtteindre 500 victoires au total."},
{"Lekakmod:voryn","Voryn","Débloquer Ossyr.\nAtteindre 500 victoires au total."},
{"Lekakmod:rakhan","Rakhan","Débloquer Solkar.\nGagner 10 duels contre Solkar."},
{"Lekakmod:krozak","Krozak","Débloquer Luneth.\nGagner 10 duels contre Luneth."},
{"Lekakmod:varnek","Varnek","Débloquer Voryn.\nGagner 10 duels contre Voryn."},
{"Lekakmod:zhyr","Zhyr","Débloquer Rakhan, Krozak et Varnek.\nGagner 20 duels contre chacun de ces trois duellistes."},
{"Lekakmod:skorath","Skorath","Débloquer Rakhan, Krozak et Varnek.\nGagner 20 duels contre chacun de ces trois duellistes."},
{"Lekakmod:vezra","Vezra","Débloquer Rakhan, Krozak et Varnek.\nGagner 20 duels contre chacun de ces trois duellistes."},
{"Lekakmod:lesub","LeSub","Débloquer les 37 autres nouveaux duellistes.\nGagner au moins un duel contre chacun."},
{"Lekakmod:yem","Yem","Débloquer les 37 autres nouveaux duellistes.\nGagner au moins un duel contre chacun."},
{"Lekakmod:lekak","Lekak","Débloquer les 37 autres nouveaux duellistes.\nGagner au moins un duel contre chacun."},
};
