typedef struct {int kind;const char *ref;int target;const char *fr,*en;} ProgressCondition;
static const int progress_counts[40]={1,1,1,1,1,1,1,2,2,5,3,3,3,3,3,3,2,2,2,2,4,4,2,2,2,4,4,4,2,2,2,2,2,2,6,6,6,2,2,2};
static const ProgressCondition progress_conditions[40][6]={
{{0,"Heishin",1,"Victoires Heishin","Wins vs Heishin"}},
{{0,"Pegasus",15,"Victoires Pegasus","Wins vs Pegasus"}},
{{0,"Lekakmod:dark-simon",5,"Victoires Dark Simon","Wins vs Dark Simon"}},
{{4,"82",1,"Red-eyes B. Dragon possédé","Red-eyes B. Dragon owned"}},
{{1,"",100,"Victoires au total","Total wins"}},
{{0,"Nitemare",1,"Victoires Nitemare","Wins vs Nitemare"}},
{{5,"first6",6,"Premiers duellistes débloqués","First duelists unlocked"}},
{{5,"first6",6,"Premiers duellistes débloqués","First duelists unlocked"},{0,"Lekakmod:primal-rex",10,"Victoires Primal Rex","Wins vs Primal Rex"}},
{{5,"first6",6,"Premiers duellistes débloqués","First duelists unlocked"},{0,"Lekakmod:soul-reaper-bakura",10,"Victoires Soul Reaper Bakura","Wins vs Soul Reaper Bakura"}},
{{2,"Lekakmod:tyrant-kaiba",1,"Tyrant Kaiba débloqué","Tyrant Kaiba unlocked"},{2,"Lekakmod:vorthrax",1,"Vorthrax débloqué","Vorthrax unlocked"},{2,"Lekakmod:nemerys",1,"Némérys débloqué","Némérys unlocked"},{0,"Lekakmod:vorthrax",5,"Victoires Vorthrax","Wins vs Vorthrax"},{0,"Lekakmod:nemerys",5,"Victoires Némérys","Wins vs Némérys"}},
{{2,"Lekakmod:ignaroth",1,"Ignaroth débloqué","Ignaroth unlocked"},{0,"Lekakmod:ignaroth",5,"Victoires Ignaroth","Wins vs Ignaroth"},{1,"",200,"Victoires au total","Total wins"}},
{{2,"Lekakmod:ignaroth",1,"Ignaroth débloqué","Ignaroth unlocked"},{0,"Lekakmod:ignaroth",5,"Victoires Ignaroth","Wins vs Ignaroth"},{1,"",200,"Victoires au total","Total wins"}},
{{2,"Lekakmod:ignaroth",1,"Ignaroth débloqué","Ignaroth unlocked"},{0,"Lekakmod:ignaroth",5,"Victoires Ignaroth","Wins vs Ignaroth"},{1,"",200,"Victoires au total","Total wins"}},
{{2,"Lekakmod:vesper",1,"Vesper débloqué","Vesper unlocked"},{7,"",200,"Cartes différentes découvertes","Different cards discovered"},{0,"Lekakmod:vesper",10,"Victoires Vesper","Wins vs Vesper"}},
{{2,"Lekakmod:azhur",1,"Azhur débloqué","Azhur unlocked"},{7,"",200,"Cartes différentes découvertes","Different cards discovered"},{0,"Lekakmod:azhur",10,"Victoires Azhur","Wins vs Azhur"}},
{{2,"Lekakmod:ferron",1,"Ferron débloqué","Ferron unlocked"},{7,"",200,"Cartes différentes découvertes","Different cards discovered"},{0,"Lekakmod:ferron",10,"Victoires Ferron","Wins vs Ferron"}},
{{2,"Lekakmod:tharn",1,"Tharn débloqué","Tharn unlocked"},{3,"Lekakmod:terrorking-archfiend",1,"@card","@card"}},
{{2,"Lekakmod:tharn",1,"Tharn débloqué","Tharn unlocked"},{3,"Lekakmod:card-54",1,"@card","@card"}},
{{2,"Lekakmod:tharn",1,"Tharn débloqué","Tharn unlocked"},{3,"443",1,"@card","@card"}},
{{2,"Lekakmod:zerak",1,"Zerak débloqué","Zerak unlocked"},{1,"",300,"Victoires au total","Total wins"}},
{{2,"Lekakmod:nekris",1,"Nékris débloqué","Nékris unlocked"},{0,"Lekakmod:vesper",10,"Victoires Vesper","Wins vs Vesper"},{0,"Lekakmod:azhur",10,"Victoires Azhur","Wins vs Azhur"},{0,"Lekakmod:ferron",10,"Victoires Ferron","Wins vs Ferron"}},
{{2,"Lekakmod:oryx",1,"Oryx débloqué","Oryx unlocked"},{0,"Lekakmod:nerex",10,"Victoires Néréx","Wins vs Néréx"},{0,"Lekakmod:ravok",10,"Victoires Ravok","Wins vs Ravok"},{0,"Lekakmod:tharn",10,"Victoires Tharn","Wins vs Tharn"}},
{{2,"Lekakmod:drazhen",1,"Drazhen débloqué","Drazhen unlocked"},{3,"34",1,"Saggi the Dark Clown découvert","Saggi the Dark Clown found"}},
{{2,"Lekakmod:drazhen",1,"Drazhen débloqué","Drazhen unlocked"},{3,"34",1,"Saggi the Dark Clown découvert","Saggi the Dark Clown found"}},
{{2,"Lekakmod:drazhen",1,"Drazhen débloqué","Drazhen unlocked"},{3,"34",1,"Saggi the Dark Clown découvert","Saggi the Dark Clown found"}},
{{2,"Lekakmod:malvek",1,"Malvek débloqué","Malvek unlocked"},{2,"Lekakmod:nyss",1,"Nyss débloqué","Nyss unlocked"},{2,"Lekakmod:krag",1,"Krag débloqué","Krag unlocked"},{6,"retail39",39,"Adversaires de base battus","Original opponents beaten"}},
{{2,"Lekakmod:malvek",1,"Malvek débloqué","Malvek unlocked"},{2,"Lekakmod:nyss",1,"Nyss débloqué","Nyss unlocked"},{2,"Lekakmod:krag",1,"Krag débloqué","Krag unlocked"},{6,"retail39",39,"Adversaires de base battus","Original opponents beaten"}},
{{2,"Lekakmod:malvek",1,"Malvek débloqué","Malvek unlocked"},{2,"Lekakmod:nyss",1,"Nyss débloqué","Nyss unlocked"},{2,"Lekakmod:krag",1,"Krag débloqué","Krag unlocked"},{6,"retail39",39,"Adversaires de base battus","Original opponents beaten"}},
{{2,"Lekakmod:velkor",1,"Velkôr débloqué","Velkôr unlocked"},{1,"",500,"Victoires au total","Total wins"}},
{{2,"Lekakmod:nharos",1,"Nharos débloqué","Nharos unlocked"},{1,"",500,"Victoires au total","Total wins"}},
{{2,"Lekakmod:ossyr",1,"Ossyr débloqué","Ossyr unlocked"},{1,"",500,"Victoires au total","Total wins"}},
{{2,"Lekakmod:solkar",1,"Solkar débloqué","Solkar unlocked"},{0,"Lekakmod:solkar",10,"Victoires Solkar","Wins vs Solkar"}},
{{2,"Lekakmod:luneth",1,"Luneth débloqué","Luneth unlocked"},{0,"Lekakmod:luneth",10,"Victoires Luneth","Wins vs Luneth"}},
{{2,"Lekakmod:voryn",1,"Voryn débloqué","Voryn unlocked"},{0,"Lekakmod:voryn",10,"Victoires Voryn","Wins vs Voryn"}},
{{2,"Lekakmod:rakhan",1,"Rakhan débloqué","Rakhan unlocked"},{2,"Lekakmod:krozak",1,"Krozak débloqué","Krozak unlocked"},{2,"Lekakmod:varnek",1,"Varnek débloqué","Varnek unlocked"},{0,"Lekakmod:rakhan",20,"Victoires Rakhan","Wins vs Rakhan"},{0,"Lekakmod:krozak",20,"Victoires Krozak","Wins vs Krozak"},{0,"Lekakmod:varnek",20,"Victoires Varnek","Wins vs Varnek"}},
{{2,"Lekakmod:rakhan",1,"Rakhan débloqué","Rakhan unlocked"},{2,"Lekakmod:krozak",1,"Krozak débloqué","Krozak unlocked"},{2,"Lekakmod:varnek",1,"Varnek débloqué","Varnek unlocked"},{0,"Lekakmod:rakhan",20,"Victoires Rakhan","Wins vs Rakhan"},{0,"Lekakmod:krozak",20,"Victoires Krozak","Wins vs Krozak"},{0,"Lekakmod:varnek",20,"Victoires Varnek","Wins vs Varnek"}},
{{2,"Lekakmod:rakhan",1,"Rakhan débloqué","Rakhan unlocked"},{2,"Lekakmod:krozak",1,"Krozak débloqué","Krozak unlocked"},{2,"Lekakmod:varnek",1,"Varnek débloqué","Varnek unlocked"},{0,"Lekakmod:rakhan",20,"Victoires Rakhan","Wins vs Rakhan"},{0,"Lekakmod:krozak",20,"Victoires Krozak","Wins vs Krozak"},{0,"Lekakmod:varnek",20,"Victoires Varnek","Wins vs Varnek"}},
{{5,"new37",37,"Nouveaux duellistes débloqués","New duelists unlocked"},{6,"new37",37,"Nouveaux duellistes battus","New duelists beaten"}},
{{5,"new37",37,"Nouveaux duellistes débloqués","New duelists unlocked"},{6,"new37",37,"Nouveaux duellistes battus","New duelists beaten"}},
{{5,"new37",37,"Nouveaux duellistes débloqués","New duelists unlocked"},{6,"new37",37,"Nouveaux duellistes battus","New duelists beaten"}},
};
